//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jquery_Mvc_Paging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ItemCode { get; set; }
        public float Price { get; set; }
        public string IME { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string PhotoUrl { get; set; }
        public bool IsPublished { get; set; }
        public bool IsNewTag { get; set; }
        public bool IsSoldTag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsReport { get; set; }
        public bool IsDelete { get; set; }
        public string Description { get; set; }
        public string CustomizedView { get; set; }
        public string Colors { get; set; }
        public Nullable<int> BrandId { get; set; }
    }
}
